### PR TITLE
Added travis-ci integration

### PR DESCRIPTION
**Pull request by degustaf**
Make sure to sign up for an account at https://travis-ci.org/ and set it to monitor shownoter

### CODE REVIEW

**Comment by jamalhansen** [comment]
@degustaf you are not messing around with TOX testing! 

I like it, but I am curious about the duplicated commits.

**Comment by degustaf** [comment]
@jamalhansen I didn't notice the double commits. That's a bad rebase. I even forgot to do the dance.

**Comment by jcode89** [comment]
@degustaf How could you forget to dance!

**Comment by jamalhansen** [comment]
Well you can dance if you want to.

https://www.youtube.com/watch?v=AjPau5QYtYs

**Comment by jcode89** [comment]
YAASSSS!!! That's what I thought of when I read that line. 😂

**Pull request merged**
